import '../models/receipt.dart';

/// Hardcoded receipt list used by the mock backend path
/// (`--dart-define=USE_MOCK_BACKEND=true`, debug builds only).
List<Receipt> mockReceipts() {
  return [
    Receipt(
      id: 'r1',
      invoiceNumber: 'INV-1042',
      date: '2026-05-08',
      businessName: 'דלק תחנת תל אביב',
      amount: 234.50,
      vat: 34.05,
      startTime: null,
      endTime: null,
      projectName: null,
      category: ReceiptCategory.vehicle,
      items: const [],
      confidence: 0.97,
      boundingBox: const BoundingBox(
        yMin: 0.02,
        xMin: 0.02,
        yMax: 0.32,
        xMax: 0.48,
      ),
    ),
    Receipt(
      id: 'r2',
      invoiceNumber: '94732',
      date: '2026-05-07',
      businessName: 'חניון עזריאלי',
      amount: 45.0,
      vat: 6.54,
      startTime: '09:30',
      endTime: '13:15',
      projectName: null,
      category: ReceiptCategory.parking,
      items: const [],
      confidence: 0.92,
      boundingBox: const BoundingBox(
        yMin: 0.02,
        xMin: 0.52,
        yMax: 0.32,
        xMax: 0.98,
      ),
    ),
    Receipt(
      id: 'r3',
      invoiceNumber: 'A-77821',
      date: '2026-05-06',
      businessName: 'קפה לנדוור',
      amount: 89.0,
      vat: null,
      startTime: null,
      endTime: null,
      projectName: null,
      category: ReceiptCategory.foodHospitality,
      items: const [
        ReceiptItem(
          code: null,
          description: 'קפה הפוך גדול',
          quantity: 2,
          price: 32,
        ),
        ReceiptItem(
          code: null,
          description: 'כריך גבינה',
          quantity: 1,
          price: 25,
        ),
      ],
      confidence: 0.78,
      boundingBox: const BoundingBox(
        yMin: 0.36,
        xMin: 0.02,
        yMax: 0.66,
        xMax: 0.48,
      ),
    ),
    Receipt(
      id: 'r4',
      invoiceNumber: '7700123',
      date: '2026-05-05',
      businessName: 'קרפור סניף רמת גן',
      amount: 312.40,
      vat: 45.40,
      startTime: null,
      endTime: null,
      projectName: null,
      category: ReceiptCategory.foodHospitality,
      items: const [
        ReceiptItem(
          code: '7290000000017',
          description: 'חלב תנובה 3% 1 ליטר',
          quantity: 1,
          price: 6.90,
        ),
        ReceiptItem(
          code: '7290000000017',
          description: 'חלב תנובה 3% 1 ליטר',
          quantity: 1,
          price: 6.90,
        ),
        ReceiptItem(
          code: '7290008580013',
          description: 'לחם אחיד פרוס',
          quantity: 2,
          price: 13.80,
        ),
        ReceiptItem(
          code: null,
          description: 'הנחת מועדון',
          quantity: 1,
          price: -4.20,
        ),
      ],
      confidence: 0.88,
      boundingBox: const BoundingBox(
        yMin: 0.36,
        xMin: 0.52,
        yMax: 0.66,
        xMax: 0.98,
      ),
    ),
    Receipt(
      id: 'r5',
      invoiceNumber: 'GC-2026-04-9931',
      date: '2026-05-04',
      businessName: 'Google Cloud',
      amount: 287.43,
      vat: 41.76,
      startTime: null,
      endTime: null,
      projectName: null,
      category: ReceiptCategory.softwareCommunications,
      items: const [
        ReceiptItem(
          code: null,
          description: 'Compute Engine — n2-standard-4',
          quantity: 1,
          price: 198.20,
        ),
        ReceiptItem(
          code: null,
          description: 'Cloud Storage egress',
          quantity: 1,
          price: 47.45,
        ),
        ReceiptItem(
          code: null,
          description: 'Gemini API usage',
          quantity: 1,
          price: 41.78,
        ),
      ],
      confidence: 0.95,
      boundingBox: const BoundingBox(
        yMin: 0.70,
        xMin: 0.02,
        yMax: 0.98,
        xMax: 0.48,
      ),
    ),
    Receipt(
      id: 'r6',
      invoiceNumber: '20260501-7700',
      date: '2026-05-01',
      businessName: 'בזק - חברת התקשורת',
      amount: 156.90,
      vat: 22.80,
      startTime: null,
      endTime: null,
      projectName: null,
      category: ReceiptCategory.softwareCommunications,
      items: const [],
      confidence: 0.91,
      boundingBox: const BoundingBox(
        yMin: 0.70,
        xMin: 0.52,
        yMax: 0.98,
        xMax: 0.98,
      ),
    ),
  ];
}
